stages:
  prepare_points:
    cmd: Rscript src/stages/prepare_points.R
    deps:
    - ${prepare_points.cities_in_file}
    - src/stages/prepare_points.R
    outs:
    - ${prepare_points.cities_out_file}:
        persist: true

  process:
    cmd: Rscript src/stages/process.R
    deps:
    - ${prepare_points.cities_out_file}
    - ${process.main_e_obs_netcdf}
    - ${process.cds_e_obs_europe_01_2022_01_01__2022_07_31_netcdf}
    - src/stages/process.R
    outs:
    - ${process.climatology_data}:
        persist: true

  evaluate_2_cities_in_month:
    cmd: Rscript src/stages/evaluate_2_cities_in_month.R
    deps:
    - ${process.climatology_data}
    - src/stages/evaluate_2_cities_in_month.R
    params:
      - evaluate_2_cities_in_month.the_2_cities
      - evaluate_2_cities_in_month.month
    outs:
    - ${evaluate_2_cities_in_month.out.graph_file_svg}:
        persist: true
    - ${evaluate_2_cities_in_month.out.graph_dir_plotly}:
        persist: true
    - ${evaluate_2_cities_in_month.out.graph_r_obj_plotly}:
        persist: true

  generate_web:
    cmd: quarto render ${generate_web.in.quarto_file}
    deps:
    - ${generate_web.in.quarto_file}
    outs:
    - ${generate_web.out.web_dir}:
        persist: true 

  evaluate_decades_means:
    cmd: Rscript src/stages/evaluate_decades_means.R
    deps:
    - ${process.climatology_data}
    - src/stages/evaluate_decades_means.R
    outs:
    - ${evaluate_decades_means.out.graph_file_svg}:
        persist: true
    #- ${evaluate_decades_means.out.graph_dir_plotly}:
    #    persist: true
    #- ${evaluate_decades_means.out.graph_r_obj_plotly}:
    #    persist: true     