stages:
  prepare_points:
    cmd: Rscript src/stages/prepare_points.R
    deps:
    - ${prepare_points.cities_in_file}
    - src/prepare_points.R
    outs:
    - ${prepare_points.cities_out_file}:
        persist: true

  # train_model:
  #   cmd: python src/train_model.py
  #   deps:
  #   - config/main.yaml
  #   - config/model
  #   - data/processed
  #   - src/train_model.py
  #   outs:
  #   - data/final:
  #       persist: true
  #   - models:
  #       persist: true
