global:
 # global parameters

prepare_points:
  cities_in_file: "data/raw/worldcities.csv"
  cities_out_file: "data/processed/worldcities.csv"

process:
  climatology_data: "data/processed/climatology_dat.csv"
  # Main official data
  main_e_obs_netcdf: 'remote-data/tg_ens_mean_0.1deg_reg_v25.0e.nc'
  # Latest data not yet added to the official release
  cds_e_obs_europe_01_2022_01_01__2022_07_31_netcdf: 'remote-data/tg_0.1deg_day_2022_grid_ensmean.nc'

evaluate_2_cities_in_month:
  evaluated_data: "data/evaluated/2_cities_in_month_evaluated_data.csv"
  the_2_cities: ["Burgos", "Sevilla"]
  month: 7
  out:
    graph_file_svg: "graphs/evaluate_2_cities_in_month.svg"
    graph_dir_plotly: "graphs/evaluate_2_cities_in_month_plotly"
    graph_r_obj_plotly: "graphs/evaluate_2_cities_in_month_plotly.rds"
