global:
 # global parameters

prepare_points:
  cities_in_file: "data/raw/worldcities.csv"
  cities_out_file: "data/processed/worldcities.csv"
  cities_exclude: ["Las Palmas", "Santa Cruz", "Cádiz"]

process:
  climatology_data: "data/processed/climatology_dat.csv"
  # Main official data
  main_e_obs_netcdf: 'remote-data/tg_ens_mean_0.1deg_reg_v25.0e.nc'
  # Latest data not yet added to the official release
  cds_e_obs_europe_01_2022_01_01__2022_07_31_netcdf: 'remote-data/tg_0.1deg_day_2022_grid_ensmean.nc'

evaluate_2_cities_in_month:
  the_2_cities: ["Burgos", "Sevilla"]
  month: 7
  out:
    graph_file_svg: "graphs/evaluate_2_cities_in_month.svg"
    graph_dir_plotly: "graphs/evaluate_2_cities_in_month_plotly"
    graph_r_obj_plotly: "graphs/evaluate_2_cities_in_month_plotly.rds"

evaluate_2_cities_in_month_1:
  the_2_cities: ["Burgos", "Sevilla"]
  month: 1
  out:
    graph_file_svg: "graphs/evaluate_2_cities_in_month_1.svg"
    graph_dir_plotly: "graphs/evaluate_2_cities_in_month_1_plotly"
    graph_r_obj_plotly: "graphs/evaluate_2_cities_in_month_1_plotly.rds"    

evaluate_decades_means:
  month: 7
  out:
    graph_file_svg: "graphs/evaluate_decades_means.svg"
    #graph_dir_plotly: "graphs/evaluate_decades_means_plotly"
    #graph_r_obj_plotly: "graphs/evaluate_decades_means.rds"    

evaluate_decades_means_botton_10:
  month: 7
  out:
    graph_file_svg: "graphs/evaluate_decades_means_botton_10.svg"
    #graph_dir_plotly: "graphs/evaluate_decades_means_botton_10_plotly"
    #graph_r_obj_plotly: "graphs/evaluate_decades_means_botton_10.rds"       

generate_web:
  in:
    quarto_file: "climatology_web.qmd"
  out:
    web_dir: "_site"




