global:
 # global parameters

prepare_points:
  cities_in_file: "data/raw/worldcities.csv"
  cities_out_file: "data/processed/worldcities.csv"

process:
  climatology_data: "data/processed/climatology_dat.csv"
  # Main official data
  main_e_obs_netcdf: 'remote-data/tg_ens_mean_0.1deg_reg_v25.0e.nc'
  # Latest data not yet added to the official release
  cds_e_obs_europe_01_2022_01_01__2022_07_31_netcdf: 'remote-data/tg_0.1deg_day_2022_grid_ensmean.nc'

set_up:
 # Parameters to setup the project

data:
  cities_csv: "data/raw/worldcities.csv"
  cds_e_obs_europe_0.1_v25.0e_netcdf: 'data/raw/tg_ens_mean_0.1deg_reg_v25.0e.nc'
  cds_e_obs_europe_0.1_2022_01_01__2022_07_31_netcdf: 'data/raw/tg_0.1deg_day_2022_grid_ensmean.nc'
  plot_set_path: 'data/processed/climatologies_spain_cities_eobs_1950_2022_dat.csv'
  # dataset_csv: 'data/raw/iris.csv'
  # features_path: 'data/processed/featured_iris.csv'
  # test_size: 0.2
  # trainset_path: 'data/processed/train_iris.csv'
  # testset_path: 'data/processed/test_iris.csv'

train:
  clf_params:
    'C': 0.001
    'solver': 'lbfgs'
    'multi_class': 'multinomial'
    'max_iter': 100
  model_path: 'models/model.joblib'

reports:
  metrics_file: 'reports/metrics.json'
  confusion_matrix_image: 'reports/confusion_matrix.png'
