# Create a file with only the capitals cities of the provinces of spain.

stages:

  download_worldcities_zip:
    cmd: 
      - mkdir -p ${root_dir}/data/raw/cities/
      - wget https://simplemaps.com/static/data/world-cities/basic/simplemaps_worldcities_basicv1.75.zip -O ${root_dir}/data/raw/cities/simplemaps_worldcities_basicv1.75.zip
    params:
      - root_dir
    outs:
    - ${root_dir}/data/raw/cities/simplemaps_worldcities_basicv1.75.zip:
        persist: true

  unzip_worldcities_zip:
    cmd:
      - mkdir -p ${root_dir}/data/processed/cities/all 
      - rm ${root_dir}/data/processed/cities/all/*
      - unzip ${root_dir}/data/raw/cities/simplemaps_worldcities_basicv1.75.zip -d ${root_dir}/data/processed/cities/all/
    deps:
    - ${root_dir}/data/raw/cities/simplemaps_worldcities_basicv1.75.zip
    params:
      - root_dir
    outs:
    - ${root_dir}/data/processed/cities/all/:
        persist: true
